from __future__ import annotations

import os


LIVE_SERVICE_ENV_VARS = (
    "FIRECRAWL_API_KEY",
    "AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT",
    "AZURE_DOCUMENT_INTELLIGENCE_KEY",
    "AZURE_SEARCH_ENDPOINT",
    "AZURE_SEARCH_API_KEY",
    "AZURE_SEARCH_INDEX_NAME",
    "AZURE_OPENAI_ENDPOINT",
    "AZURE_OPENAI_API_KEY",
    "AZURE_OPENAI_EMBEDDING_DEPLOYMENT",
    "AZURE_OPENAI_API_VERSION",
    "LANGSMITH_API_KEY",
)


LIVE_CLOUD_ENABLED = os.getenv("ALLERNAV_LIVE_CLOUD_TESTS", "").lower() in {"1", "true", "yes"}

if not LIVE_CLOUD_ENABLED:
    for env_var in LIVE_SERVICE_ENV_VARS:
        os.environ[env_var] = ""

    os.environ["LANGSMITH_TRACING"] = "false"
